egovernments/health-campaign-config

egov-indexer/product-indexer.yml
egov-persister/product-persister.yml

Product persister config - includes product and product-varaint.

[hlm-699]: Product persister config - includes product and product-variant. 

---

egov-indexer/individual-indexer.yml
egov-indexer/product-indexer.yml
egov-indexer/project-indexer.yml
egov-persister/individual-persister.yml

Some modifications in indexers for product and project as per convention

[hlm-621] - Individual config

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-1622 | Bednets distribution

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-1620 | household kpi for Overview dashboard

---

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

chart-tabs fix

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

donut-chart | overview page

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

show label

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

Use new filterForCurrentDay config field to get data for current day

HLM-1783 : Replace hard coded current date range

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

[DEV] sort-value by desc for coverage ranking

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

Show footer for summary chart

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

HLM-1882 | Insights enabled for date range

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

summary for complaints daywise

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-2023 | Open complaints summary chart

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

Drilldown till Village Complaints summary boundary

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

coverage ranking drilldown(OVERVIEW)

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

bednets not delivered barchart drilldown(R&D page)

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-2073 | Bednets not delivered drill down

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

complaints-summary drilldown fixes

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

empty-drill-down

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-1572-LatLong- household and warehouse

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

Bug fix: Limit target on metric cards

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

Lat long maps refactoring

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

actual and planned line graph - Bednets and population

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

HLM-2590 | National bugs

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

lat-long charts fixes

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-2641 | actual vs planned line graph

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

Merge DEV to QA

---

egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

HLM-2590 | Production bugs

---

egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

row-nums-fix
